version: "3.9"

services:
  app:
    image: docker.io/trlong/myblazorapp:latest
    container_name: myblazorapp
    restart: always
    ports:
      - "3000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge